# Label requests
@baseUrl = http://localhost:8000
@user = admin
@password = F@k3P@ssw0rd

## Create new Label
POST {{baseUrl}}/api/v1/labels
content-type: application/json
Authorization: Basic {{user}}:{{password}}

{
    "name": "Car",
    "category": "Vehicle"
}
###

## Get all labels
GET {{baseUrl}}/api/v1/labels
Authorization: Basic {{user}}:{{password}}
###

## Update label
PUT {{baseUrl}}/api/v1/labels/4
content-type: application/json
Authorization: Basic {{user}}:{{password}}

{
    "name": "Bike"
}
###

## Delete label
DELETE {{baseUrl}}/api/v1/labels/4
Authorization: Basic {{user}}:{{password}}


###

# Image request

## Upload image
POST {{baseUrl}}/api/v1/images
Authorization: Basic {{user}}:{{password}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="car.png"
Content-Type: image/png

< ./demo/images/car.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

## Get list images
GET {{baseUrl}}/api/v1/images
Authorization: Basic {{user}}:{{password}}
###

## Get one image
GET {{baseUrl}}/api/v1/images/1
Authorization: Basic {{user}}:{{password}}
###

## Delete image
DELETE  {{baseUrl}}/api/v1/images/1
Authorization: Basic {{user}}:{{password}}
###

# Tag request

## Get all tags from image

GET {{baseUrl}}/api/v1/images/2/tags
Authorization: Basic {{user}}:{{password}}
###

## Create new Tag
POST {{baseUrl}}/api/v1/images/7/tags
Authorization: Basic {{user}}:{{password}}
content-type: application/json

{
    "label_id": 5,
    "position": {
        "top": 100,
        "left": 100,
        "width": 100,
        "height": 100
    }
}
###

## Get tag item
GET {{baseUrl}}/api/v1/tags/1
Authorization: Basic {{user}}:{{password}}
###

## Update tag item
PUT {{baseUrl}}/api/v1/tags/1
Authorization: Basic {{user}}:{{password}}
content-type: application/json

{
    "position": {
        "top": 100,
        "left": 100,
        "width": 200,
        "height": 200
    }
}
###

## Delete tag item
DELETE {{baseUrl}}/api/v1/tags/1
Authorization: Basic {{user}}:{{password}}
###